### PR TITLE
Dockerized and Updated Project

### PR DESCRIPTION
**Pull request by Humoud**
Hi,

The following are the changes which I've made:

1. Update YARA to v4.1.0.
2. Update requirements.txt, requests lib was missing and thus I added it.
3. Dockerize project:
 3.1. Moved code to app/ folder
 3.2. Created dockerfile along with docker-compose.yml.
 3.3. Using the official elasticsearch docker container image instead of installing elasticsearch.

4. Updated README to include usage via docker.

### CODE REVIEW

**Review by Audition-CSBlock — APPROVED** [review]
LGTM! The final size of the container will be big, but i don't know of any improvements that could change that.

**Comment by Humoud** [comment]
@Audition-CSBlock  Awesome!
Now, regarding the docker image sizes on disk, the following is the break down of them:
1. Inhale image: _879MB_
2. Elasticsearch Image: _851MB_

Both add up to : _1.73GB_ disk space

I have a strong feeling that it is possible to reduce the size of the inhale image, and I will work on that.

Just thought I would shed more light on the size situation of the project :)

**Comment by Audition-CSBlock** [comment]
@Humoud Yup, i looked into your fork and saw the sizes. I'll also look into improvements for that some other time :), amazing work!

**Comment by Humoud** [comment]
@Audition-CSBlock thank you :)

**Pull request merged**
